In [5]:
import sys
from pathlib import Path

import pandas as pd
from IPython.display import display
working_directory = Path.cwd().resolve()

project_root = next(
    (
        path
        for path in (working_directory, *working_directory.parents)
        if (path / "src" / "procesado" / "limpiar_poblacion.py").is_file()
    ),
    None,
)
if project_root is None:
    raise FileNotFoundError("Could not find the project root containing src/procesado.")
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# 1. Cleaning population

Read the Andalusian population Bronze table, apply the current cleaning steps, and preview the result.

In [6]:
from src.common.storage import read_csv_dataset, s3_uri_for
from src.procesado.pipeline import clean_and_upload_population
from src.procesado.common.paths import POPULATION_BRONZE_PATH

population_bronze = read_csv_dataset(
    POPULATION_BRONZE_PATH,
    s3_uri=s3_uri_for(POPULATION_BRONZE_PATH.name, "raw/data"),
    dtype=str,
    keep_default_na=False,
)
population_cleaned = clean_and_upload_population(population_bronze)
print(
    f"Bronze rows: {len(population_bronze):,}; "
    f"cleaned rows: {len(population_cleaned):,}; "
    "outputs persisted according to SAVE_LOCALLY and SAVE_S3"
)
display(population_cleaned.head(10))

Could not read s3://sot-05-market-expansion/raw/data/population_andalusia.csv from S3; falling back to local file C:\Users\fatima.d.villalba\OneDrive - Accenture\Desktop\repos\market-expansion-sot\data\raw\population_andalusia.csv: Unable to locate credentials

Bronze rows: 1,201,050; cleaned rows: 3,925; outputs persisted according to SAVE_LOCALLY and SAVE_S3

,province_code,province,municipality_code,municipality_name,year,population_total,population_18_50,source,downloaded_at_utc
0,04,Almería,04001,Abla,2021,1260,479,INE,2026-10-21 10:04:25.436037+00:00
1,04,Almería,04001,Abla,2022,1248,474,INE,2026-10-21 10:04:25.436037+00:00
2,04,Almería,04001,Abla,2023,1259,474,INE,2026-10-21 10:04:25.436037+00:00
3,04,Almería,04001,Abla,2024,1277,480,INE,2026-10-21 10:04:25.436037+00:00
4,04,Almería,04001,Abla,2025,1267,464,INE,2026-10-21 10:04:25.436037+00:00
5,04,Almería,04002,Abrucena,2021,1212,461,INE,2026-10-21 10:04:25.436037+00:00
6,04,Almería,04002,Abrucena,2022,1220,464,INE,2026-10-21 10:04:25.436037+00:00
7,04,Almería,04002,Abrucena,2023,1274,475,INE,2026-10-21 10:04:25.436037+00:00
8,04,Almería,04002,Abrucena,2024,1234,442,INE,2026-10-21 10:04:25.436037+00:00
9,04,Almería,04002,Abrucena,2025,1235,442,INE,2026-10-21 10:04:25.436037+00:00

# 2. Cleaning income

Read the INE Bronze table, keep per-person income, save the Silver Parquet, and preview the result.

In [12]:
from src.procesado.pipeline import clean_and_upload_income
from src.procesado.common.paths import INCOME_BRONZE_PATH

income_bronze = read_csv_dataset(
    INCOME_BRONZE_PATH,
    s3_uri=s3_uri_for(INCOME_BRONZE_PATH.name, "raw/data"),
    dtype=str,
    keep_default_na=False,
)
income_cleaned = clean_and_upload_income(income_bronze)
print(
    f"Bronze rows: {len(income_bronze):,}; "
    f"cleaned rows: {len(income_cleaned):,}; "
    "outputs persisted according to SAVE_LOCALLY and SAVE_S3"
)
display(income_cleaned.head(10))

Could not read s3://sot-05-market-expansion/raw/data/income_andalusia.csv from S3; falling back to local file C:\Users\fatima.d.villalba\OneDrive - Accenture\Desktop\repos\market-expansion-sot\data\raw\income_andalusia.csv: Unable to locate credentials

Bronze rows: 786; cleaned rows: 783; outputs persisted according to SAVE_LOCALLY and SAVE_S3

,province_code,province,municipality_code,municipality_name,year,mean_net_income_per_person,source,downloaded_at_utc
0,04,Almería,04001,Abla,2024,12836,INE,2026-10-21 10:06:54.459332+00:00
1,04,Almería,04002,Abrucena,2024,12565,INE,2026-10-21 10:06:54.459332+00:00
2,04,Almería,04003,Adra,2024,10965,INE,2026-10-21 10:06:54.459332+00:00
3,04,Almería,04004,Albanchez,2024,12885,INE,2026-10-21 10:06:54.459332+00:00
4,04,Almería,04005,Alboloduy,2024,11848,INE,2026-10-21 10:06:54.459332+00:00
5,04,Almería,04006,Albox,2024,11145,INE,2026-10-21 10:06:54.459332+00:00
6,04,Almería,04007,Alcolea,2024,11594,INE,2026-10-21 10:06:54.459332+00:00
7,04,Almería,04008,Alcóntar,2024,14087,INE,2026-10-21 10:06:54.459332+00:00
8,04,Almería,04009,Alcudia de Monteagud,2024,15878,INE,2026-10-21 10:06:54.459332+00:00
9,04,Almería,04010,Alhabia,2024,10916,INE,2026-10-21 10:06:54.459332+00:00

# 3. Cleaning gyms

Read the Andalusian OSM Bronze gym table, clean it, save the GeoParquet Silver table, and preview the result.

In [7]:
from src.procesado.pipeline import clean_and_upload_gyms
from src.procesado.common.paths import GYMS_BRONZE_PATH

gyms_bronze = read_csv_dataset(
    GYMS_BRONZE_PATH,
    s3_uri=s3_uri_for(GYMS_BRONZE_PATH.name, "raw/data"),
    dtype=str,
    keep_default_na=False,
)
gyms_cleaned = clean_and_upload_gyms(gyms_bronze)
print(
    f"Bronze rows: {len(gyms_bronze):,}; "
    f"Silver rows: {len(gyms_cleaned):,}; "
    f"gyms: {gyms_cleaned['sport_centre_type'].eq('gym').sum():,}; "
    f"other sports facilities: "
    f"{gyms_cleaned['sport_centre_type'].eq('other_sport_facility').sum():,}; "
    "outputs persisted according to SAVE_LOCALLY and SAVE_S3"
)
display(gyms_cleaned.head(10))

Could not read s3://sot-05-market-expansion/raw/data/gyms_andalusia.csv from S3; falling back to local file C:\Users\fatima.d.villalba\OneDrive - Accenture\Desktop\repos\market-expansion-sot\data\raw\gyms_andalusia.csv: Unable to locate credentials

Bronze rows: 3,569; Silver rows: 3,569; gyms: 565; other sports facilities: 3,004; outputs persisted according to SAVE_LOCALLY and SAVE_S3

,osm_type,osm_id,province_code,province,latitude,longitude,source,downloaded_at_utc,tag_name,tag_sport,sport_centre_type,geometry
0,node,260812441,ES-AL,Almería,37.172028,-1.833994,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Go-Karting,karting,other_sport_facility,POINT (-1.83399 37.17203)
1,node,1620487480,ES-AL,Almería,37.345363,-2.432541,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Pabellón,<NA>,other_sport_facility,POINT (-2.43254 37.34536)
2,node,1912986759,ES-AL,Almería,37.212201,-1.810827,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Vera Costa,fitness,other_sport_facility,POINT (-1.81083 37.2122)
3,node,2452253961,ES-AL,Almería,36.838087,-2.949279,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Pabellon de deportes,<NA>,other_sport_facility,POINT (-2.94928 36.83809)
4,node,4432638479,ES-AL,Almería,36.969974,-2.607533,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Frontón de Huécija,pelota,other_sport_facility,POINT (-2.60753 36.96997)
5,node,4512584749,ES-AL,Almería,36.838962,-2.460986,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,e-fitness,<NA>,gym,POINT (-2.46099 36.83896)
6,node,4512664045,ES-AL,Almería,36.839466,-2.456743,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,BOX GYM,<NA>,gym,POINT (-2.45674 36.83947)
7,node,4708078896,ES-AL,Almería,36.696758,-2.789563,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Be in Shape,<NA>,gym,POINT (-2.78956 36.69676)
8,node,5319369078,ES-AL,Almería,37.352822,-2.183695,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Gimnasio municipal,<NA>,gym,POINT (-2.18369 37.35282)
9,node,5319369079,ES-AL,Almería,37.352754,-2.183941,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Pabellón Municipal de Deportes,<NA>,other_sport_facility,POINT (-2.18394 37.35275)

# 4. Cleaning municipality boundaries

Read the CNIG Bronze CSV, clean the boundaries, and persist the Silver GeoParquet according to the storage settings.

In [9]:
from src.procesado.common.paths import MUNICIPALITY_BOUNDARIES_BRONZE_PATH
from src.procesado.pipeline import clean_and_upload_municipality_boundaries

cnig_bronze = read_csv_dataset(
    MUNICIPALITY_BOUNDARIES_BRONZE_PATH,
    s3_uri=s3_uri_for(MUNICIPALITY_BOUNDARIES_BRONZE_PATH.name, "raw/data"),
    dtype=str,
    keep_default_na=False,
)
cnig_cleaned = clean_and_upload_municipality_boundaries(cnig_bronze)
print(
    f"Silver municipality boundaries: {len(cnig_cleaned):,}; "
    "outputs persisted according to SAVE_LOCALLY and SAVE_S3"
)
display(cnig_cleaned.head(10))

Could not read s3://sot-05-market-expansion/raw/data/municipality_boundaries_andalusia.csv from S3; falling back to local file C:\Users\fatima.d.villalba\OneDrive - Accenture\Desktop\repos\market-expansion-sot\data\raw\municipality_boundaries_andalusia.csv: Unable to locate credentials

Silver municipality boundaries: 785; outputs persisted according to SAVE_LOCALLY and SAVE_S3

,municipality_code,cnig_national_code,municipality_name,geometry,source,loaded_at_utc
0,04001,34010404001,Abla,"MULTIPOLYGON (((-2.78452 37.0935, -2.7841 37.0...",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
1,04002,34010404002,Abrucena,"MULTIPOLYGON (((-2.88868 37.09169, -2.8886 37....",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
2,04003,34010404003,Adra,"MULTIPOLYGON (((-3.14019 36.78779, -3.13982 36...",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
3,04004,34010404004,Albanchez,"MULTIPOLYGON (((-2.20218 37.31223, -2.20177 37...",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
4,04005,34010404005,Alboloduy,"MULTIPOLYGON (((-2.71288 37.07817, -2.71128 37...",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
5,04006,34010404006,Albox,"MULTIPOLYGON (((-2.21616 37.45233, -2.21296 37...",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
6,04007,34010404007,Alcolea,"MULTIPOLYGON (((-3.07193 36.91929, -3.07161 36...",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
7,04008,34010404008,Alcóntar,"MULTIPOLYGON (((-2.65763 37.22892, -2.65825 37...",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
8,04009,34010404009,Alcudia de Monteagud,"MULTIPOLYGON (((-2.27371 37.2416, -2.27355 37....",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00
9,04010,34010404010,Alhabia,"MULTIPOLYGON (((-2.59703 36.99498, -2.5969 36....",IGN/CNIG BDDAE,2026-10-21 12:48:52.061476+00:00

# 5 Crossing gym and municipalities tables

In [10]:
from src.procesado.pipeline import cross_and_upload_gyms_municipalities

gyms_with_municipality = cross_and_upload_gyms_municipalities(
    gyms_cleaned,
    cnig_cleaned,
)
assigned_municipalities = int(
    gyms_with_municipality['municipality_code'].notna().sum()
)
print(
    f"Gyms with municipality assigned: {assigned_municipalities:,} / "
    f"{len(gyms_with_municipality):,}; "
    "output persisted according to SAVE_LOCALLY and SAVE_S3"
)
display(gyms_with_municipality.head(10))

Gyms with municipality assigned: 3,569 / 3,569; output persisted according to SAVE_LOCALLY and SAVE_S3

,osm_type,osm_id,province_code,province,latitude,longitude,source,downloaded_at_utc,tag_name,tag_sport,sport_centre_type,geometry,municipality_code,municipality_name
0,node,260812441,ES-AL,Almería,37.172028,-1.833994,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Go-Karting,karting,other_sport_facility,POINT (-1.83399 37.17203),04049,Garrucha
1,node,1620487480,ES-AL,Almería,37.345363,-2.432541,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Pabellón,<NA>,other_sport_facility,POINT (-2.43254 37.34536),04092,Tíjola
2,node,1912986759,ES-AL,Almería,37.212201,-1.810827,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Vera Costa,fitness,other_sport_facility,POINT (-1.81083 37.2122),04100,Vera
3,node,2452253961,ES-AL,Almería,36.838087,-2.949279,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Pabellon de deportes,<NA>,other_sport_facility,POINT (-2.94928 36.83809),04029,Berja
4,node,4432638479,ES-AL,Almería,36.969974,-2.607533,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Frontón de Huécija,pelota,other_sport_facility,POINT (-2.60753 36.96997),04051,Huécija
5,node,4512584749,ES-AL,Almería,36.838962,-2.460986,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,e-fitness,<NA>,gym,POINT (-2.46099 36.83896),04013,Almería
6,node,4512664045,ES-AL,Almería,36.839466,-2.456743,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,BOX GYM,<NA>,gym,POINT (-2.45674 36.83947),04013,Almería
7,node,4708078896,ES-AL,Almería,36.696758,-2.789563,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Be in Shape,<NA>,gym,POINT (-2.78956 36.69676),04902,El Ejido
8,node,5319369078,ES-AL,Almería,37.352822,-2.183695,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Gimnasio municipal,<NA>,gym,POINT (-2.18369 37.35282),04031,Cantoria
9,node,5319369079,ES-AL,Almería,37.352754,-2.183941,OpenStreetMap,2026-10-20 15:31:28.373903+00:00,Pabellón Municipal de Deportes,<NA>,other_sport_facility,POINT (-2.18394 37.35275),04031,Cantoria

# 6 GOLD aggregated table

In [13]:
from src.procesado.tabla_oro import create_and_upload_gold_table

gold_municipalities = create_and_upload_gold_table(
    population_cleaned,
    income_cleaned,
    gyms_with_municipality,
)
print(f"Gold municipality table created with {len(gold_municipalities):,} rows.")
display(gold_municipalities.head(10))

Gold municipality table created with 785 rows.

,municipality_code,municipality_name,province_code,province,population_year,population_total,population_18_50,population_growth_start_year,population_growth_pct,income_year,mean_net_income_per_person,gyms_count,other_sports_facilities_count
0,04001,Abla,04,Almería,2025,1267,464,2021,0.555556,2024,12836,0,1
1,04002,Abrucena,04,Almería,2025,1235,442,2021,1.89769,2024,12565,0,0
2,04003,Adra,04,Almería,2025,25579,11849,2021,0.380661,2024,10965,6,9
3,04004,Albanchez,04,Almería,2025,684,174,2021,-5.0,2024,12885,0,0
4,04005,Alboloduy,04,Almería,2025,578,216,2021,-5.863192,2024,11848,0,0
5,04006,Albox,04,Almería,2025,12872,5392,2021,4.345006,2024,11145,3,12
6,04007,Alcolea,04,Almería,2025,831,285,2021,-2.579132,2024,11594,0,1
7,04008,Alcóntar,04,Almería,2025,551,178,2021,0.181818,2024,14087,0,0
8,04009,Alcudia de Monteagud,04,Almería,2025,117,38,2021,-8.59375,2024,15878,0,0
9,04010,Alhabia,04,Almería,2025,750,334,2021,10.782866,2024,10916,1,1

# 7. Data quality: one row per source

Raw record counts, null-key rates, and duplicates are measured before cleaning. A null-key record has at least one blank required key field; duplicate counts are extra records sharing a source key. Cross percentages are cleaned records matched to Gold divided by cleaned records eligible for the cross. Municipality candidate and retention counts expose losses from source filters, and unmatched records include their treatment.

In [ ]:
from src.procesado.tabla_calidad import create_and_upload_quality_table

quality_report = create_and_upload_quality_table(
    population_bronze,
    population_cleaned,
    income_bronze,
    income_cleaned,
    gyms_bronze,
    gyms_cleaned,
    cnig_bronze,
    cnig_cleaned,
    gyms_with_municipality,
    gold_municipalities,
)
print('Quality table persisted according to SAVE_LOCALLY and SAVE_S3.')
display(quality_report)